name: flutter_movie_code_test
description: "Code test for Flutter Developer position"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluentui_system_icons: ^1.1.258
  # state management
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  # generators
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  retrofit: ^4.1.0
  # database
  sqflite: ^2.3.3+2
  path_provider: ^2.1.4
  path: ^1.9.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8 # dart run build_runner build --delete-conflicting-outputs
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.2

flutter:
  uses-material-design: true
